### ISSUE TITLE
Exception when drawing state diagram

### ISSUE THREAD

**Issue by Ondra09** [skuro/plantuml-mode#122]
When trying to draw this code:
```

@startuml

[*] --> State1
State1 --> [*]

@enduml
```

getting this exception in txt mode

```
java.lang.IllegalStateException
	at net.sourceforge.plantuml.cucadiagram.dot.AbstractGraphviz.createFile3(AbstractGraphviz.java:102)
	at net.sourceforge.plantuml.posimo.GraphvizSolverB.solve(GraphvizSolverB.java:104)
	at net.sourceforge.plantuml.cucadiagram.dot.CucaDiagramTxtMaker.<init>(CucaDiagramTxtMaker.java:115)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.createFilesTxt(CucaDiagram.java:675)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:625)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:201)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:158)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:113)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:359)
	at net.sourceforge.plantuml.Run.main(Run.java:166)
```

# Checklist for pull requests

- [ X ] I'm fine with my code being released under the GPLv2 license
- [ ] the pull request is filed against the `develop` branch instead of `master`

**Comment by skuro** [comment]
no stale please
